package helper

const (
	STRING_NUMBER 			= "0123456789"
	STRING_ALPHABET_LOWER	= "abcdefghijklmnopqrstuvwxyz"
	STRING_ALPHABET_UPPER	= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	STRING_ALPHANUMERIC 	= STRING_ALPHABET_LOWER + STRING_ALPHABET_UPPER + STRING_NUMBER
)