package constant

const STRING_NUMBER 		= "0123456789"
const STRING_ALPHABET_LOWER	= "abcdefghijklmnopqrstuvwxyz"
const STRING_ALPHABET_UPPER	= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const STRING_ALPHANUMERIC 	= STRING_ALPHABET_LOWER + STRING_ALPHABET_UPPER + STRING_NUMBER